### PR TITLE
Add other chain services

### PR DESCRIPTION
**Pull request by MasterPi-2124**
Add Gaia, SentinelHub, Akash, Anon, Beach, Chain-main, Dig, OmniFlixhub, Persistencecore, Regen, Starname, Juno, Sifnode.

Remain: Kava, IOV, V-Systems, Desmos, Stakebird, Luna, Turbogeth, BSC, Peercoin, Blurt.

How do you get the variables?

### CODE REVIEW

**Review by faddat — CHANGES_REQUESTED** [review]
Systemd doesn't have a concept of $HOME, so that won't resolve.  

I think we can run these services as the user chains, so that data will always be in ~/.chain.

Do you have a machine to test this on?

It is good work.  Thank you. 

So the change I'm requesting is to please add the creation of a user chains to the stand up script and run these all is the user chains and specify the home environment very well because Cosmo chainz will crash if they can't find that

**Comment by MasterPi-2124** [comment]
Sure, thanks for that information. I tested on the server and Pi.

**Comment by faddat** [comment]
Already tested and it worked?

If so, I was wrong and that is great, and we can merge :).

**Comment by faddat** [comment]
Hey, tell you what-- Please test them and make the modifications around running as user `chains`.  

Thank you!

**Pull request merged**
